name: github pages

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - run: npm ci
    - run: npm run build
    - run: npm run export
    - run: find out -type f -exec md5sum {} \; | sort | md5sum > out/version.txt
    - run: '[[ $(curl -s https://allegro.tech/version.txt) != $(cat out/version.txt) ]]'
    - run: touch out/.nojekyll
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        cname: allegro.tech
